# Generated by Django 4.2.9 on 2024-03-04 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must be Alphanumeric', regex='^[a-zA-Z0-9_-]*$')])),
                ('weight', models.FloatField()),
                ('code', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_code', message='upper case letters, underscore, and numbers allowed', regex='^[A-Z0-9_]*$')])),
                ('image', models.ImageField(blank=True, upload_to='medication_images')),
            ],
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('model', models.CharField(choices=[('Lightweight', 'Lightweight'), ('Middleweight', 'Middleweight'), ('Cruiserweight', 'Cruiserweight'), ('Heavyweight', 'Heavyweight')], default='Lightweight', max_length=13)),
                ('weight_limit', models.FloatField(default=500)),
                ('battery_capacity', models.IntegerField()),
                ('state', models.CharField(choices=[('IDLE', 'IDLE'), ('LOADING', 'LOADING'), ('LOADED', 'LOADED'), ('DELIVERING', 'DELIVERING'), ('DELIVERED', 'DELIVERED'), ('RETURNING', 'RETURNING')], default='IDLE', max_length=10)),
                ('current_medication_weight', models.FloatField(default=0)),
                ('medications', models.ManyToManyField(related_name='drones', to='drones.medication')),
            ],
        ),
    ]
