# Generated by Django 4.2.9 on 2024-03-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='current_medication_weight',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='drone',
            name='state',
            field=models.CharField(blank=True, choices=[('IDLE', 'IDLE'), ('LOADING', 'LOADING'), ('LOADED', 'LOADED'), ('DELIVERING', 'DELIVERING'), ('DELIVERED', 'DELIVERED'), ('RETURNING', 'RETURNING')], default='IDLE', max_length=10),
        ),
    ]
