# Generated by Django 4.2.9 on 2024-03-04 21:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0003_alter_drone_medications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='battery_capacity',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(code='invalid_battery_capacity', message='Battery capacity must be a number between 0 and 100', regex='^(?:[0-9]|[1-9][0-9]|100)$')]),
        ),
    ]
